basePath: /api/v1
host: 127.0.0.1:8085
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API12222
  version: "1.0"
paths:
  /check:
    get:
      description: 服务初始连接测试  接口描述
      responses: {}
      summary: 服务连接校验  接口简介
  /hello:
    get:
      description: 服务初始连接测试  接口描述
      responses: {}
      summary: 服务连接校验  接口简介
  /test:
    get:
      consumes:
      - application/json
      description: 接口描述信息
      parameters:
      - description: name value
        in: path
        name: name
        type: string
      responses:
        "200":
          description: '{"code":200, "message":"success"}'
        "400":
          description: '{"code":400, "message":"success"}'
          schema:
            type: string
        "404":
          description: '{"code":404, "message":"success"}'
          schema:
            type: string
        "500":
          description: '{"code":500, "message":"success"}'
          schema:
            type: string
      security:
      - Bearer: []
      summary: 首页接口摘要信息
      tags:
      - 用户信息
swagger: "2.0"
